### ISSUE TITLE
Define a clear distinction between Surface and Layer

### ISSUE THREAD

**Issue by MMavrov** [OctalS/libconutils#2]
Currently the differences between those two are not completely clear in my opinion.

It should be said in the documentation that the difference is simply ideological. I.e.
- S is a **surface** for its children
- S is a **layer** for its parent

**Comment by MMavrov** [comment]
Alternative solution would be to remove the usage of **layer** at all. It seems a bit unnecessary when you think about it. 
This approach will require a bit more work in order to change all the methods definitions to use **surface** instead. For example:
_addLayer()_ -> _addSurface()_

**Comment by OctalS** [comment]
addLayer is the correct name here.  For the user a Surface is always a Surface no mather where it is applied to.
The name Layer is only within the context of the Surface itself.
Let's not change this. If you have some concerns about the meaning please update the documentation to clear this.
