### ISSUE TITLE
Start using the color and attributes enums from Char

### ISSUE THREAD

**Issue by MMavrov** [OctalS/libconutils#3]
For example turn:
`Char(char val = ' ', uint8_t fg = 7, uint8_t bg = 0, uint8_t attr = none)`
into
`Char(char val = ' ', uint8_t fg = white, uint8_t bg = black, uint8_t attr = none)`

**Comment by OctalS** [comment]
Thanks. Please submit a change.

**Comment by OctalS** [comment]
Fixed in 30eab4e
