### ISSUE TITLE
Rename the method

### ISSUE THREAD

**Issue by MMavrov** [OctalS/libconutils#5]
https://github.com/OctalS/libconutils/blob/33f76bf5633d25c5c6a0a558105a2e7a502a2a57/conutils.h#L209

In my opinion this method should be renamed to something like:
`getLinearCoordinate`
`getLinCoord`
or something like this.

The inverse operation - get the 2d coordinates from a linear index:
`getRectCoordinate` ..

**Comment by OctalS** [comment]
Sounds good but the methods names seems a bit long. Can you think of something without the 'get' prefix so we can be in line with the current style?
I propose the following:
size_t index_for(const Point& point);
Point point_for(size_t index);

**Comment by OctalS** [comment]
Fix in merge commit: 30eab4e

**Comment by OctalS** [comment]
Fixed in ac7a307
